
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[319] =
    {   0,
        0,    0,    0,    0,   28,   27,   26,   25,   24,   18,
       16,   15,   23,   27,   16,   10,   18,   19,   18,   11,
       11,   11,   11,   11,   11,   11,   11,   15,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   15,   27,   18,   17,   22,   13,    6,
        0,   10,   15,   21,    0,   11,    0,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,    2,   11,   11,   11,   11,
       11,   11,    2,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,    7,   20,    0,   13,    0,    9,    0,    0,    0,
       12,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,    2,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   14,    0,
        0,    5,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,    2,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,    5,    5,    5,   11,   11,   11,
       11,   11,    4,   11,   11,   11,   11,   11,   11,   11,
       11,   11,    2,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    2,   11,   11,
       11,   11,   11,   11,    4,    3,    2,   11,   11,   11,
       11,   11,   11,   11,    2,   11,   11,   11,   11,   11,
        8,   11,   11,   11,   11,   11,   11,   11,    0,   11,
       11,   11,    0,    1,    0,   11,    0,   11,   11,   11,
       11,   11,   11,   11,   11,    0,   11,    0,    0,    0,
       12,   11,   11,   11,   11,   11,    0,   11,    0,    0,

        5,   11,   11,    0,    5,    5,    5,   11,    0,   11,
        0,    0,    0,    0,    4,    4,    4,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    6,    7,    1,    8,
        9,   10,    6,   11,    6,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   11,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   18,   22,
       18,   18,   23,   18,   18,   18,   24,   18,   18,   18,
       18,   18,   25,   18,   18,   18,   18,   18,   18,   18,
       26,    1,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   18,   39,   40,   41,   42,
       43,   44,   18,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   11,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    1,    1,    6,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[334] =
    {   0,
        0,    0,  457,  453,  459, 1103, 1103, 1103, 1103,  418,
      390,  397, 1103,    0,   47,  389,   43,  386,   45,   56,
       57,   58,   59,   61,   62,   60,   63, 1103,   65,   71,
       91,   86,   67,   98,  111,  100,  114,  119,  124,  125,
      131,  139,   66,  342,  364,  356, 1103, 1103,  362, 1103,
      365,  349, 1103, 1103,  352,   72,  309,  148,  153,  152,
      155,  158,  161,  162,  163,  177,  178,  184,  185,  186,
      188,  187,  210,  189,  194,  213,  217,  218,  220,  222,
      229,  224,  230,  233,  234,  244,  245,  239,  250,  265,
      267,  270,  271,  275,  280,  287,  276,  296,  286,  302,

      301, 1103, 1103,  322,  292,  284, 1103,  276,  126,  247,
      241,  303,  307,  318,  324,  311,  322,  327,  338,  343,
      347,  348,  349,  350,  352,  363,  354,  374,  375,  379,
      384,  385,  386,  390,  388,  399,  400,  405,  415,  409,
      420,  422,  424,  425,  428,  429,  430,  431,  436,  445,
      434,  456,  439,  458,  461,  472,  478,  481, 1103,  145,
      197,  236,  468,  483,  484,  485,  489,  488,  491,  504,
      508,  510,  511,  515,  514,  520,  518,  521,  523,  534,
      540,  543,  544,  548,  555,  551,  557,  564,  550,  567,
      578,  580,  565,  584,  586,  590,  592,  593,  594,  597,

      599,  605,  609,  613,  245,  253,  312,  614,  622,  619,
      624,  629,    0,  633,  634,  635,  638,  644,  650,  654,
      663,  658,  660,  664,  669,  670,  673,  675,  685,  680,
      694,  696,  705,  706,  699,  707,  709,  710,  711,  722,
      716,  726,  731,  737,    0,  743,  753,  742,  745,  751,
      754,  758,  759,  762,  811,  768,  767,  764,  860,  861,
      781,  862,  863,  864,  865,  783,  866,  867,  214,  870,
      873,  876,  246, 1103,   69,    0,   78,  875,  895,  896,
      900,  904,  905,  902,  906,  153,  907,  213,  916,  320,
      364,  912,  908,  915,  931,  937,  143,  935,  947,  949,

      956,  940,  954,  147,  964,  965,  968,  956,  111,  961,
       97,   92,   83,   66,   37,   34,    0, 1103, 1022, 1025,
     1029, 1032, 1036, 1042, 1048, 1054, 1060, 1066, 1072, 1078,
     1084, 1090, 1096
    } ;

static yyconst flex_int16_t yy_def[334] =
    {   0,
      318,    1,  319,  319,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  320,  318,  318,  318,  318,  318,  321,
      321,  321,  321,  321,  321,  321,  321,  318,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  318,  318,  318,  318,  318,  322,  318,
      323,  318,  318,  318,  324,  321,  325,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  318,  318,  318,  322,  323,  318,  324,  326,  325,
      325,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  318,  326,
      326,  327,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  327,  327,  327,  321,  321,  321,
      321,  321,  328,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  328,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  318,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  318,  321,
      321,  321,  329,  318,  330,  255,  331,  321,  321,  321,
      321,  321,  321,  321,  321,  318,  321,  330,  332,  331,
      331,  321,  321,  321,  321,  321,  318,  321,  332,  332,

      333,  321,  321,  318,  333,  333,  333,  321,  318,  321,
      318,  318,  318,  318,  328,  328,  328,    0,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318
    } ;

static yyconst flex_uint16_t yy_nxt[1160] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   11,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,    6,    6,   28,   20,   29,
       30,   31,   32,   33,   34,   20,   20,   35,   20,   36,
       20,   37,   20,   38,   39,   40,   41,   20,   42,   43,
       20,   20,   20,   13,   44,   28,   50,   53,   46,   51,
       46,   53,   47,   55,   55,   55,   55,   55,   55,   55,
       55,  274,   55,   55,   55,  317,  316,  289,   55,   55,
      274,   57,   57,   57,   57,   57,   57,   57,   57,   63,
       57,   57,   57,   55,   59,   66,   57,   57,   55,   58,

       61,   60,  101,   62,  291,   55,   77,   55,   78,   64,
       67,   57,  315,   68,   65,   69,   57,   79,   55,   75,
       71,   55,   70,   57,  314,   57,   55,   72,   76,  313,
       73,   55,   55,   74,  161,   80,   57,   81,   55,   57,
       82,  312,   86,   87,   57,   83,   55,   88,   89,   57,
       57,   84,   85,  161,  311,   55,   57,   92,  309,   55,
       55,   93,   55,   90,   57,   55,   91,   98,   55,   55,
       55,   94,   95,   57,   96,   99,   97,   57,   57,  162,
       57,  100,  113,   57,   55,   55,   57,   57,   57,  304,
      112,   55,   55,   55,   55,   55,   55,  115,  162,  114,

      297,   55,   57,   57,  116,  161,  118,  117,  119,   57,
       57,   57,   57,   57,   57,  274,  127,   55,  123,   57,
       55,  289,  120,  121,   55,   55,  122,   55,  130,   55,
      129,   55,  124,  125,  126,   57,   55,   55,   57,  128,
       55,   55,   57,   57,  206,   57,   55,   57,  274,   57,
      162,   55,   55,  206,   57,   57,  286,   55,   57,   57,
      131,  206,  132,  135,   57,  133,  134,  111,   83,   57,
       57,  136,   55,  111,   55,   57,  137,   55,   55,  138,
      139,  142,   55,   55,  109,  140,  107,   55,   83,  207,
       57,  141,   57,   55,   55,   57,   57,  145,  207,  104,

       57,   57,  143,   55,  148,   57,  207,  144,   55,   55,
       55,   57,   57,  147,   55,  155,  146,  152,   55,  149,
      206,   57,  274,  150,  151,   55,   57,   57,   57,   55,
      159,   55,   57,  153,   55,  111,   57,   83,  158,  156,
      154,  157,  163,   57,  167,   55,  291,   57,  165,   57,
       55,  164,   57,  166,   55,   55,   55,   55,  168,   55,
      109,   55,   52,   57,  169,  207,  274,  107,   57,  104,
       55,  103,   57,   57,   57,   57,  102,   57,  174,   57,
      172,   55,   55,  175,  170,   83,   55,  173,   57,  171,
      291,   55,   55,   55,  176,   55,   48,   55,  175,   57,

       57,   54,   52,   48,   57,   47,   55,   55,  180,   57,
       57,   57,   55,   57,  181,   57,   55,  183,   83,  177,
      178,  179,   55,  182,   57,   57,   83,   55,  184,   55,
       57,   55,   55,   46,   57,   55,   55,   55,   55,  185,
       57,   55,  186,   55,  175,   57,   55,   57,  188,   57,
       57,  187,   55,   57,   57,   57,   57,  189,  318,   57,
      190,   57,   45,   55,   57,   55,   45,  193,   55,  318,
       57,  192,  191,  197,  195,   55,  194,  196,  198,   55,
      199,   57,  318,   57,   83,   55,   57,  200,   55,  318,
       55,   55,   55,   57,  318,   55,   55,   57,   55,  213,

      201,  208,  202,   57,  175,  318,   57,  203,   57,   57,
       57,   55,  209,   57,   57,   55,   57,   55,   55,  318,
      204,   55,   55,  210,  212,   55,  318,   55,   55,   57,
       55,  211,  214,   57,  318,   57,   57,  215,  318,   57,
       57,   55,  318,   57,  218,   57,   57,   55,   57,  318,
       55,   55,  216,   83,  217,   55,   83,   55,   55,   57,
      219,  318,   55,   83,   55,   57,  318,   83,   57,   57,
      318,   55,   55,   57,   55,   57,   57,  318,  318,  221,
       57,  220,   57,  223,  222,   55,  226,   55,  224,   57,
       57,   55,   57,   55,  175,  225,  229,   55,  228,   55,

       55,   55,  232,   57,   55,   57,   55,  230,  227,   57,
      318,   57,   55,  231,  318,   57,   55,   57,   57,   57,
       55,   55,   57,  235,   57,  236,   55,  234,  233,   55,
       57,   55,  175,  237,   57,  213,   55,   83,   57,   57,
       55,   55,   55,  241,   57,   55,   83,   57,  238,   57,
      239,   55,  243,  242,   57,  240,  318,   55,   57,   57,
       57,   55,  244,   57,  248,   55,  318,   55,  246,   57,
       55,   55,  318,  249,  247,   57,   55,   55,  318,   57,
       55,  318,   55,   57,   83,   57,  318,   55,   57,   57,
      252,  250,   55,  251,   57,   57,  175,  318,   57,  253,

       57,   55,  318,   55,  254,   57,   55,  257,   83,  318,
       57,  256,   55,   55,   55,  255,   55,   55,   55,   57,
      258,   57,  318,   55,   57,  318,  259,  261,  318,   55,
       57,   57,   57,   55,   57,   57,   57,   83,   55,  318,
      260,   57,  213,   83,   55,  262,   83,   57,  264,   55,
       55,   57,   55,  263,  213,   83,   57,  266,   55,  265,
       55,   55,   57,  318,  269,   55,   55,   57,   57,   55,
       57,   55,  267,  270,   55,   55,   57,  318,   57,   57,
      318,  268,  318,   57,   57,  318,  175,   57,   55,   57,
       55,  318,   57,   57,  213,  272,  279,   83,  271,  278,

       83,  318,  318,   83,  318,  318,   57,  318,   57,  318,
       83,  273,  273,  274,  273,  273,  273,  273,  275,  273,
      273,  273,  273,  273,  276,  273,  273,  273,  276,  276,
      276,  276,  276,  276,  276,  276,  277,  273,  273,  273,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  273,  273,  273,   55,   55,   55,
       55,   55,   55,   55,   55,  318,  318,   55,  213,  318,
       55,  318,   55,   55,  318,   57,   57,   57,   57,   57,
       57,   57,   57,  261,  280,   57,  281,  283,   57,  285,

       57,   57,   55,   55,  284,  282,   83,   55,  292,   55,
      318,   55,   55,   55,   55,   55,   83,  287,  274,   55,
       57,   57,   55,  318,  300,   57,  293,   57,  261,   57,
       57,   57,   57,   57,  318,   83,  318,   57,   55,  318,
       57,   83,   55,   83,   55,  294,  295,   55,  213,  274,
      296,  274,  303,  298,  302,  300,   57,  300,  274,  318,
       57,   55,   57,   55,  306,   57,  274,  274,   55,  301,
      274,  318,  306,  306,   83,  318,  306,   83,  318,   57,
       83,   57,  318,  318,  318,  318,   57,  318,  318,  310,
      318,  318,  318,   83,  318,  318,  318,  318,  318,  318,

      301,  318,  301,  318,  318,  318,  308,  318,  318,  307,
      318,  318,  318,  318,  318,  318,  318,  307,  307,  318,
      318,  307,    6,    6,    6,    6,    6,    6,   49,  318,
       49,   56,   56,   56,  105,  105,  106,  106,  106,  106,
      106,  106,  108,  318,  108,  108,  108,  108,  110,  318,
      110,  110,  110,  110,  160,  318,  160,  160,  160,  160,
      205,  318,  205,  205,  205,  205,  245,  318,  245,  245,
      245,  245,  273,  273,  273,  273,  273,  273,  288,  288,
      288,  288,  288,  288,  290,  290,  290,  290,  290,  290,
      299,  299,  299,  299,  299,  299,  305,  305,  305,  305,

      305,  305,    5,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318
    } ;

static yyconst flex_int16_t yy_chk[1160] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,   17,   17,   15,
       19,   19,   15,   20,   21,   22,   23,   26,   24,   25,
       27,  275,   29,   43,   33,  316,  315,  275,   30,   56,
      277,   20,   21,   22,   23,   26,   24,   25,   27,   26,
       29,   43,   33,   32,   22,   29,   30,   56,   31,   21,

       24,   23,   43,   25,  277,   34,   33,   36,   33,   27,
       29,   32,  314,   30,   27,   30,   31,   33,   35,   32,
       31,   37,   30,   34,  313,   36,   38,   31,   32,  312,
       31,   39,   40,   31,  109,   34,   35,   34,   41,   37,
       34,  311,   36,   37,   38,   35,   42,   37,   38,   39,
       40,   35,   35,  160,  309,   58,   41,   39,  304,   60,
       59,   40,   61,   38,   42,   62,   38,   41,   63,   64,
       65,   40,   40,   58,   40,   41,   40,   60,   59,  109,
       61,   42,   59,   62,   66,   67,   63,   64,   65,  297,
       58,   68,   69,   70,   72,   71,   74,   61,  160,   60,

      286,   75,   66,   67,   62,  161,   64,   63,   65,   68,
       69,   70,   72,   71,   74,  288,   72,   73,   69,   75,
       76,  288,   66,   67,   77,   78,   68,   79,   75,   80,
       74,   82,   70,   71,   71,   73,   81,   83,   76,   73,
       84,   85,   77,   78,  162,   79,   88,   80,  273,   82,
      161,   86,   87,  205,   81,   83,  269,   89,   84,   85,
       76,  206,   77,   80,   88,   78,   79,  111,   82,   86,
       87,   81,   90,  110,   91,   89,   84,   92,   93,   85,
       85,   89,   94,   97,  108,   86,  106,   95,   88,  162,
       90,   87,   91,   99,   96,   92,   93,   91,  205,  105,

       94,   97,   90,   98,   94,   95,  206,   90,  101,  100,
      112,   99,   96,   93,  113,   99,   92,   97,  116,   94,
      207,   98,  290,   95,   96,  114,  101,  100,  112,  117,
      104,  115,  113,   98,  118,   57,  116,   99,  101,  100,
       98,  100,  112,  114,  116,  119,  290,  117,  114,  115,
      120,  113,  118,  115,  121,  122,  123,  124,  117,  125,
       55,  127,   52,  119,  118,  207,  291,   51,  120,   49,
      126,   46,  121,  122,  123,  124,   45,  125,  123,  127,
      121,  128,  129,  124,  119,  125,  130,  122,  126,  120,
      291,  131,  132,  133,  126,  135,   44,  134,  127,  128,

      129,   18,   16,   12,  130,   11,  136,  137,  130,  131,
      132,  133,  138,  135,  131,  134,  140,  135,  132,  128,
      129,  129,  139,  134,  136,  137,  133,  141,  136,  142,
      138,  143,  144,   10,  140,  145,  146,  147,  148,  137,
      139,  151,  137,  149,  140,  141,  153,  142,  139,  143,
      144,  138,  150,  145,  146,  147,  148,  141,    5,  151,
      142,  149,    4,  152,  153,  154,    3,  145,  155,    0,
      150,  144,  143,  149,  147,  163,  146,  148,  150,  156,
      151,  152,    0,  154,  153,  157,  155,  152,  158,    0,
      164,  165,  166,  163,    0,  168,  167,  156,  169,  168,

      154,  163,  155,  157,  156,    0,  158,  157,  164,  165,
      166,  170,  164,  168,  167,  171,  169,  172,  173,    0,
      158,  175,  174,  165,  167,  177,    0,  176,  178,  170,
      179,  166,  169,  171,    0,  172,  173,  170,    0,  175,
      174,  180,    0,  177,  173,  176,  178,  181,  179,    0,
      182,  183,  171,  174,  172,  184,  176,  189,  186,  180,
      179,    0,  185,  177,  187,  181,    0,  178,  182,  183,
        0,  188,  193,  184,  190,  189,  186,    0,    0,  181,
      185,  180,  187,  183,  182,  191,  187,  192,  185,  188,
      193,  194,  190,  195,  184,  186,  190,  196,  189,  197,

      198,  199,  193,  191,  200,  192,  201,  191,  188,  194,
        0,  195,  202,  192,    0,  196,  203,  197,  198,  199,
      204,  208,  200,  197,  201,  199,  210,  196,  194,  209,
      202,  211,  195,  200,  203,  211,  212,  198,  204,  208,
      214,  215,  216,  208,  210,  217,  204,  209,  201,  211,
      202,  218,  210,  209,  212,  203,    0,  219,  214,  215,
      216,  220,  212,  217,  216,  222,    0,  223,  214,  218,
      221,  224,    0,  218,  215,  219,  225,  226,    0,  220,
      227,    0,  228,  222,  217,  223,    0,  230,  221,  224,
      222,  219,  229,  220,  225,  226,  221,    0,  227,  223,

      228,  231,    0,  232,  224,  230,  235,  227,  228,    0,
      229,  226,  233,  234,  236,  225,  237,  238,  239,  231,
      229,  232,    0,  241,  235,    0,  230,  232,    0,  240,
      233,  234,  236,  242,  237,  238,  239,  234,  243,    0,
      231,  241,  243,  236,  244,  235,  233,  240,  239,  248,
      246,  242,  249,  237,  246,  238,  243,  241,  250,  240,
      247,  251,  244,    0,  247,  252,  253,  248,  246,  254,
      249,  258,  242,  248,  257,  256,  250,    0,  247,  251,
        0,  244,    0,  252,  253,    0,  249,  254,  261,  258,
      266,    0,  257,  256,  266,  254,  257,  258,  250,  256,

      251,    0,    0,  252,    0,    0,  261,    0,  266,    0,
      253,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  259,  260,  262,
      263,  264,  265,  267,  268,    0,    0,  270,  268,    0,
      271,    0,  278,  272,    0,  259,  260,  262,  263,  264,
      265,  267,  268,  259,  260,  270,  262,  264,  271,  267,

      278,  272,  279,  280,  265,  263,  271,  281,  278,  284,
        0,  282,  283,  285,  287,  293,  270,  272,  289,  292,
      279,  280,  294,    0,  289,  281,  279,  284,  280,  282,
      283,  285,  287,  293,    0,  284,    0,  292,  295,    0,
      294,  293,  298,  281,  296,  282,  283,  302,  296,  299,
      285,  300,  294,  287,  292,  299,  295,  300,  301,    0,
      298,  303,  296,  308,  301,  302,  305,  306,  310,  289,
      307,    0,  305,  306,  302,    0,  307,  295,    0,  303,
      298,  308,    0,    0,    0,    0,  310,    0,    0,  308,
        0,    0,    0,  310,    0,    0,    0,    0,    0,    0,

      299,    0,  300,    0,    0,    0,  303,    0,    0,  301,
        0,    0,    0,    0,    0,    0,    0,  305,  306,    0,
        0,  307,  319,  319,  319,  319,  319,  319,  320,    0,
      320,  321,  321,  321,  322,  322,  323,  323,  323,  323,
      323,  323,  324,    0,  324,  324,  324,  324,  325,    0,
      325,  325,  325,  325,  326,    0,  326,  326,  326,  326,
      327,    0,  327,  327,  327,  327,  328,    0,  328,  328,
      328,  328,  329,  329,  329,  329,  329,  329,  330,  330,
      330,  330,  330,  330,  331,  331,  331,  331,  331,  331,
      332,  332,  332,  332,  332,  332,  333,  333,  333,  333,

      333,  333,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java.l"
#line 2 "java.l"
#include<stdio.h>
#include<string.h>

#line 832 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 24 "java.l"

#line 1053 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 319 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1103 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 25 "java.l"
printf("Importing Package \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "java.l"
printf("Keyword \t\t-->\t\t %s\n", yytext); 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "java.l"
printf("datatype \t\t-->\t\t %s\n", yytext); 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "java.l"
printf("function call \t\t-->\t\t %s\n", yytext); 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "java.l"
{
					printf("function defn \t\t-->\t\t"); 
					int i=0;
					while(yytext[i]!='{')
					{
						printf("%c",yytext[i]);
						i++;
					}
					printf("\n");
					printf("Spl char \t\t-->\t\t {\n");
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "java.l"
{ BEGIN(COMMENT); printf("Multiline comment \t\t-->\t\t %s", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "java.l"
{ BEGIN(INITIAL); printf("%s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "java.l"
printf("Access Specifiers \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 9:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 44 "java.l"
printf("Singleline Comment \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "java.l"
printf("Number \t\t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "java.l"
printf("Identifier \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "java.l"
printf("Identifier \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "java.l"
printf("Attribute call \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "java.l"
printf("Attribute function call -->\t\t %s\n", yytext);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "java.l"
printf("bitwise operator \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "java.l"
printf("Arithmetic operator \t-->\t\t %s\n", yytext);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "java.l"
printf("Arithmetic assignment operator \t-->\t\t %s\n", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "java.l"
printf("Relational operator \t-->\t\t %s\n", yytext);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "java.l"
printf("assignment operator \t-->\t\t %s\n", yytext);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "java.l"
printf("Relational assignment operator \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "java.l"
printf("Relational operator \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "java.l"
printf("Logical operator \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "java.l"
printf("Spl char \t\t-->\t\t %s\n", yytext);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "java.l"
{ } ;           /* skip whitespace */
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 60 "java.l"
{ } ;             /* skip newlines */
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "java.l"
{ } ;             /* skip tabs */
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "java.l"
ECHO;
	YY_BREAK
#line 1262 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 319 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 319 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 318);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 63 "java.l"



int yywrap(void){}

int main(int argc, char* argv[]) {
    FILE *file;

    if (argc < 2) {
        fprintf(stderr, "Usage --> %s file\n", argv[0]);
        return 1;
    }

    file = fopen(argv[1], "r");
    if (file == NULL) {
        fprintf(stderr, "Error --> Unable to open file %s\n", argv[1]);
        return 1;
    }

    yyin = file;
    yylex();

    fclose(file);
    return 0;
}

